version: '3'
services:
    web:
        restart: always
        build:
          context: .
          args:
            - SOURCE_COMMIT
        image: pbevin/wordfun:latest
        ports:
            - "3000:3000"
