name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache target directory
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-${{ hashFiles('Cargo.toml', 'Cargo.lock', 'src') }}

    - name: Run tests
      run: cargo test --verbose
